sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
services:
  - postgresql
before_script:
  - psql -c 'create database document_management_test;' -U postgres
  - NODE_ENV=test npm run migrate:test:db
script:
  - npm test
after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
addons:
  postgresql: "9.3"